<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Devolutions.Terminal.Settings.Editor</RootNamespace>
    <AssemblyName>Devolutions.Terminal.Settings.Editor</AssemblyName>
    <Description>Avalonia settings editor for Devolutions Terminal.</Description>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Devolutions.Terminal.Settings\Devolutions.Terminal.Settings.csproj" />
  </ItemGroup>
</Project>
