<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>WindowsTerminal.Cli</RootNamespace>
    <AssemblyName>wt</AssemblyName>
    <Description>Windows Terminal command-line client and activation parser.</Description>
    <PublishAot>true</PublishAot>
    <PublishTrimmed>true</PublishTrimmed>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.CommandLine" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Terminal.Settings\Terminal.Settings.csproj" />
    <ProjectReference Include="..\WindowsTerminal.Broker\WindowsTerminal.Broker.csproj" />
  </ItemGroup>
</Project>
